{{- define "helm-chart-library.ingress" -}}
{{- if .Values.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-ingress
  labels:
    {{- include "helm.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.ingress.tls.enabled -}}
  tls:
    - hosts:
      - {{ .Values.ingress.host }}
      {{ if .Values.ingress.tls.secret.create -}}
      secretName: {{ .Release.Name }}-tls-secret
      {{- else }}
      secretName: {{ .Values.ingress.tls.secret.name }}
      {{- end }}
    {{- end }}
  rules:
    - host: {{required "A host URL is required for the Gerrit Ingress. Please set 'ingress.host'" .Values.ingress.host | quote}}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .Release.Name }}-service
                port: 
                  number: {{ .Values.service.http.port }}
{{- end }}
---
{{ if and .Values.ingress.tls.enabled .Values.ingress.tls.secret.create -}}
apiVersion: v1
kind: Secret
metadata:
  name:  {{ .Release.Name }}-tls-secret
type: kubernetes.io/tls
data:
  {{ with .Values.ingress.tls -}}
  tls.crt: {{ .cert | b64enc }}
  tls.key: {{ .key | b64enc }}
  {{- end }}
{{- end }}
{{- end -}}